language: node_js
notifications:
  email: false
install: case $TRAVIS_BRANCH in greenkeeper*) npm i;; *) npm ci;; esac;
before_script:
- npm run greenkeeper:update-lockfile
before_deploy:
- git config --global user.email "$GIT_EMAIL"
- git config --global user.name "dsmJS Bot"
deploy:
- skip_cleanup: true
  provider: script
  script: npm run deploy
after_script: npm run greenkeeper:upload-lockfile
env:
  global:
  - FORCE_COLOR=1
  - NPM_CONFIG_COLOR=always
#  - GK_LOCK_COMMIT_AMEND=true
  - secure: rnYvmYNIrY7TxSTJmt/zOQ3quOzW5KL3eI0juNAbDRtphL7rNy1hkPlYS9mi3w6HlgLwNq6igq0utFljljngYyeHeDLXM9tRC2czSYwJztFWB/uim9AS0Bubah4By7HYhEoU6MkYlMFGRbhiZwpgvX7SC9fN9qomX74fNYL7ANQOX4x+MfTNXYOtmippm+HWf3lcxgdYfMMgC5VleZNllHdtD/ON7O9AwzMcWAqnOwOJQ91JPbMbGWhm29ytt6yZQ/oE0DJHj/ls02U+Dz2k6GWVJ4YQXnT16folLum5hpyyDpSfTpVTeID9LARnMlURr4TgEiWvVSBv5/PJ89NYV9VmHjc6VuGkQZSpLk3j1S+Ax4aOnPSgPThNJ8wsXHjJDc/UCtRdec4GUid48cs2uAKfsS3qJta3alt3EZvOO1TwwENqE+r5U/OQGq9WibywoOF99vfK1Lc01tBvHSLNWkMKiCuZGPuMYzrluRanx2mTnU65bw6+jEZWme6R6mqSDNSerbyN/xdIP94ttXpnitUlRHGj4YsaZKm60vWfo0T4wT5vF2NibefilWAOlNIZVLVD0T8/8rz/Ovp4b3xAcxzPOaY07m9k74ifEQ7TVKuydHRqG0vzmvHWzD+ato0kNIth5ugllqYQPE0i+ETUbksILI8Bt1bIhv2m0E+4mi4=
  - secure: DufPhM+d9GWcm7G9d9toOxP+T+Ar+dCoW4TNoqiFkTsFWMY2K8K2sjEzBEnYvJX3lA8wvgWGtJ56DCkhXayFMEz4UVTzeFidkdClmnOKl6wiDB2BgM/aNKfSoIvvk1sSNueaAp82N+j2DSRr57QY91QygVadTEwownuX6glyixG6MfSIF2dMh0/PX3R0SYpMfUppgvfQzr2LAZ+oqUxbkD/rr9YnnjOo+iJnYMS4A4J8jQCeyXJd/FwdASRoitBqQa26+J5YBx3g1NRTqm8DCcNVCM6JuqG3YI2luEUhQaoRMehWXPbWTKNKpnKRYtGu8jv91HDuhKkZK3ozt5cbpD1BGCqhLQOBUPhGidqfsUf9FnxoFjNm810n2XCW7SAwYiWWju/jiGcXCtnpAZLi4pSyDA25M8ZYL02R+QMOiHBE4ZX6fjUUnV6ViHKkcQvs0PizoR7h3OPrSnRvHSUBLsqBWmdN+RcCTqMrB9Pdc8xyNgwWMkrP4gTiGl3w2Ws6LurznQ1XwRJ8e/C7FOGzbcj8tDlSty9sB6tJ/a7WY1Mwtcpvmu40oITJ6cq/WGFMiqsYe26UJRKet81Yz37WcX5z342OYXPBK+8tmiFkygi3iBKE97IOF1b9dSjbrTZB+iEIdTWhnO4Huw5QCQWFWWSG7vAzi5nBioV1/XT7HCw=
