language: node_js
notifications:
  email: false
before_script:
- npm ls >/dev/null
- npm run greenkeeper:update-lockfile
before_deploy:
  - npm run build
  - git config --global user.email "$GIT_EMAIL"
  - git config --global user.name "dsmJS Bot"
deploy:
  - skip_cleanup: true
    provider: script
    script: npm run deploy
after_script: npm run greenkeeper:upload-lockfile
env:
  global:
    secure: rnYvmYNIrY7TxSTJmt/zOQ3quOzW5KL3eI0juNAbDRtphL7rNy1hkPlYS9mi3w6HlgLwNq6igq0utFljljngYyeHeDLXM9tRC2czSYwJztFWB/uim9AS0Bubah4By7HYhEoU6MkYlMFGRbhiZwpgvX7SC9fN9qomX74fNYL7ANQOX4x+MfTNXYOtmippm+HWf3lcxgdYfMMgC5VleZNllHdtD/ON7O9AwzMcWAqnOwOJQ91JPbMbGWhm29ytt6yZQ/oE0DJHj/ls02U+Dz2k6GWVJ4YQXnT16folLum5hpyyDpSfTpVTeID9LARnMlURr4TgEiWvVSBv5/PJ89NYV9VmHjc6VuGkQZSpLk3j1S+Ax4aOnPSgPThNJ8wsXHjJDc/UCtRdec4GUid48cs2uAKfsS3qJta3alt3EZvOO1TwwENqE+r5U/OQGq9WibywoOF99vfK1Lc01tBvHSLNWkMKiCuZGPuMYzrluRanx2mTnU65bw6+jEZWme6R6mqSDNSerbyN/xdIP94ttXpnitUlRHGj4YsaZKm60vWfo0T4wT5vF2NibefilWAOlNIZVLVD0T8/8rz/Ovp4b3xAcxzPOaY07m9k74ifEQ7TVKuydHRqG0vzmvHWzD+ato0kNIth5ugllqYQPE0i+ETUbksILI8Bt1bIhv2m0E+4mi4=
